
    <footer aria-label="Footer information">

      <hr>

      <p>&copy; 2026 Goobers. All rights reserved.</p>

      <p>
        <a href="https://student-team-dxgbe8hd.atlassian.net/jira/software/projects/SCRUM/boards/1">Jira Project</a> |
        <a href="https://github.com/Res-ro/goobers-applied-web-sustainable-energy-part2">GitHub Repository</a> |
        <a href="mailto:info@goobers.com">Email Us</a>
      </p>

    </footer>

  </body>
</html>
